"""Seed script: relationship_types, holidays, first templates."""
import asyncio
import uuid
from datetime import UTC, datetime

from app.core.database import async_session_factory
from app.models.holiday import Holiday
from app.models.relationship import RelationshipType
from app.models.template import Scene, Template, TemplateVersion

RELATIONSHIP_TYPES = [
    "parent", "child", "spouse", "partner", "friend",
    "colleague", "boss", "sibling", "grandparent", "grandchild",
    "classmate", "teacher", "relative",
]

HOLIDAYS = [
    {"code": "birthday", "title": "День рождения", "kind": "personal"},
    {"code": "new_year", "title": "Новый год", "kind": "state", "month": 1, "day": 1, "country_code": "RU"},
    {"code": "christmas", "title": "Рождество Христово", "kind": "state", "month": 1, "day": 7, "country_code": "RU"},
    {"code": "feb23", "title": "23 февраля", "kind": "state", "month": 2, "day": 23, "country_code": "RU"},
    {"code": "march8", "title": "8 марта", "kind": "state", "month": 3, "day": 8, "country_code": "RU"},
    {"code": "may1", "title": "Праздник Весны и Труда", "kind": "state", "month": 5, "day": 1, "country_code": "RU"},
    {"code": "victory_day", "title": "9 мая", "kind": "state", "month": 5, "day": 9, "country_code": "RU"},
    {"code": "russia_day", "title": "День России", "kind": "state", "month": 6, "day": 12, "country_code": "RU"},
    {"code": "unity_day", "title": "День народного единства", "kind": "state", "month": 11, "day": 4, "country_code": "RU"},
    {"code": "programmer_day", "title": "День программиста", "kind": "professional", "month": 9, "day": 13, "country_code": "RU"},
    {"code": "teacher_day", "title": "День учителя", "kind": "professional", "month": 10, "day": 5, "country_code": "RU"},
    {"code": "builder_day", "title": "День строителя", "kind": "professional", "month": 8, "day": 11, "country_code": "RU"},
    {"code": "doctor_day", "title": "День врача", "kind": "professional", "month": 6, "day": 19, "country_code": "RU"},
    {"code": "valentines", "title": "День святого Валентина", "kind": "thematic", "month": 2, "day": 14, "country_code": "RU"},
    {"code": "halloween", "title": "Хэллоуин", "kind": "thematic", "month": 10, "day": 31, "country_code": "RU"},
]

FIRST_TEMPLATES = [
    {
        "code": "classic_birthday_warm",
        "title": "Классическое тёплое поздравление",
        "description": "Универсальное тёплое поздравление с фотографиями и добрыми пожеланиями. Подходит для любого возраста.",
        "kind": "video",
        "category": "birthday",
        "occasion_codes": ["birthday"],
        "relationship_types": ["parent", "child", "spouse", "partner", "friend", "colleague", "sibling", "grandparent", "grandchild", "classmate", "teacher", "relative"],
        "moods": ["warm", "touching"],
        "tags": ["universal", "family", "classic"],
        "base_price_rub": 299,
        "cost_price_rub": 89,
        "estimated_duration_sec": 45,
        "difficulty": 1,
        "personalization_score": 7,
        "sort_order": 1,
    },
    {
        "code": "funny_friend_roast",
        "title": "Юмористический роаст для друга",
        "description": "Шуточное «нападение» на друга с добрым юмором. Идеально для близких друзей и коллег.",
        "kind": "video",
        "category": "birthday",
        "occasion_codes": ["birthday"],
        "relationship_types": ["friend", "colleague", "sibling"],
        "moods": ["funny", "playful"],
        "tags": ["humor", "friends", "roast"],
        "base_price_rub": 399,
        "cost_price_rub": 119,
        "estimated_duration_sec": 60,
        "difficulty": 2,
        "personalization_score": 8,
        "sort_order": 2,
    },
    {
        "code": "anniversary_epic",
        "title": "Юбилей — эпично",
        "description": "Эпичное поздравление для круглой даты. Торжественно и масштабно.",
        "kind": "video",
        "category": "birthday",
        "occasion_codes": ["birthday", "anniversary"],
        "relationship_types": ["parent", "child", "spouse", "partner", "friend", "colleague", "sibling", "grandparent", "grandchild", "classmate", "teacher", "relative"],
        "moods": ["epic", "warm"],
        "tags": ["anniversary", "epic", "milestone"],
        "base_price_rub": 799,
        "cost_price_rub": 239,
        "estimated_duration_sec": 60,
        "difficulty": 3,
        "personalization_score": 8,
        "sort_order": 3,
    },
    {
        "code": "new_year_family",
        "title": "Новогоднее семейное поздравление",
        "description": "Тёплое новогоднее поздравление с ёлкой, подарками и семейным уютом.",
        "kind": "video",
        "category": "holiday",
        "occasion_codes": ["new_year"],
        "relationship_types": ["parent", "child", "spouse", "grandparent", "grandchild"],
        "moods": ["festive", "warm"],
        "tags": ["new_year", "family", "holiday"],
        "base_price_rub": 349,
        "cost_price_rub": 104,
        "estimated_duration_sec": 50,
        "difficulty": 2,
        "personalization_score": 6,
        "sort_order": 10,
    },
    {
        "code": "new_year_wishes",
        "title": "Новый год — поздравление",
        "description": "Универсальное новогоднее поздравление для всех. С Дедом Морозом и Снегурочкой.",
        "kind": "video",
        "category": "holiday",
        "occasion_codes": ["new_year"],
        "relationship_types": ["parent", "child", "spouse", "partner", "friend", "colleague", "sibling", "grandparent", "grandchild", "classmate", "teacher", "relative"],
        "moods": ["festive", "warm", "funny"],
        "tags": ["new_year", "universal", "holiday"],
        "base_price_rub": 599,
        "cost_price_rub": 179,
        "estimated_duration_sec": 50,
        "difficulty": 1,
        "personalization_score": 6,
        "sort_order": 11,
    },
    {
        "code": "march8_women",
        "title": "8 марта — женщине",
        "description": "Нежное поздравление к 8 марта с цветами и весенним настроением.",
        "kind": "video",
        "category": "holiday",
        "occasion_codes": ["march8"],
        "relationship_types": ["spouse", "parent", "colleague", "friend"],
        "moods": ["warm", "romantic"],
        "tags": ["womens_day", "spring", "flowers"],
        "base_price_rub": 599,
        "cost_price_rub": 179,
        "estimated_duration_sec": 45,
        "difficulty": 1,
        "personalization_score": 7,
        "sort_order": 12,
    },
    {
        "code": "feb23_men",
        "title": "23 февраля — мужчине",
        "description": "Брутальное поздравление к 23 февраля с военной тематикой и силой.",
        "kind": "video",
        "category": "holiday",
        "occasion_codes": ["feb23"],
        "relationship_types": ["spouse", "parent", "colleague", "friend"],
        "moods": ["brutal", "official"],
        "tags": ["defenders_day", "military", "men"],
        "base_price_rub": 599,
        "cost_price_rub": 179,
        "estimated_duration_sec": 45,
        "difficulty": 2,
        "personalization_score": 7,
        "sort_order": 13,
    },
    {
        "code": "space_captain_birthday",
        "title": "Космический капитан",
        "description": "Эпическое поздравление в стиле космической одиссеи. Именинник — капитан звездолёта.",
        "kind": "video",
        "category": "cinematic",
        "occasion_codes": ["birthday", "anniversary"],
        "relationship_types": ["parent", "spouse", "partner"],
        "moods": ["epic", "warm"],
        "tags": ["space", "scifi", "cinematic"],
        "base_price_rub": 699,
        "cost_price_rub": 209,
        "estimated_duration_sec": 60,
        "difficulty": 3,
        "personalization_score": 9,
        "sort_order": 20,
    },
    {
        "code": "secret_agent_birthday",
        "title": "Секретная операция",
        "description": "Шпионский триллер с именинником в роли секретного агента. Миссия — спасти праздник.",
        "kind": "video",
        "category": "cinematic",
        "occasion_codes": ["birthday"],
        "relationship_types": ["friend", "colleague", "classmate"],
        "moods": ["funny", "brutal"],
        "tags": ["spy", "action", "thriller"],
        "base_price_rub": 699,
        "cost_price_rub": 209,
        "estimated_duration_sec": 50,
        "difficulty": 3,
        "personalization_score": 9,
        "sort_order": 21,
    },
    {
        "code": "hollywood_trailer",
        "title": "Голливудский трейлер",
        "description": "Поздравление в стиле голливудского блокбастера. Красные дорожки и премьеры.",
        "kind": "video",
        "category": "cinematic",
        "occasion_codes": ["birthday", "anniversary"],
        "relationship_types": ["parent", "child", "spouse", "partner", "friend", "colleague", "sibling", "grandparent", "grandchild", "classmate", "teacher", "relative"],
        "moods": ["epic", "official"],
        "tags": ["hollywood", "premiere", "glamour"],
        "base_price_rub": 799,
        "cost_price_rub": 239,
        "estimated_duration_sec": 60,
        "difficulty": 3,
        "personalization_score": 8,
        "sort_order": 22,
    },
    {
        "code": "oscar_award",
        "title": "Оскар",
        "description": "Церемония вручения Оскара. Именинник — главный номинант вечера.",
        "kind": "video",
        "category": "cinematic",
        "occasion_codes": ["birthday", "anniversary", "achievement"],
        "relationship_types": ["parent", "child", "spouse", "partner", "friend", "colleague", "sibling", "grandparent", "grandchild", "classmate", "teacher", "relative"],
        "moods": ["epic", "official"],
        "tags": ["oscar", "award", "ceremony"],
        "base_price_rub": 799,
        "cost_price_rub": 239,
        "estimated_duration_sec": 55,
        "difficulty": 3,
        "personalization_score": 8,
        "sort_order": 23,
    },
    {
        "code": "space_mission",
        "title": "Космическая миссия",
        "description": "Именинник — астронавт на МКС. Поздравление из космоса.",
        "kind": "video",
        "category": "cinematic",
        "occasion_codes": ["birthday", "new_year"],
        "relationship_types": ["friend", "partner", "spouse"],
        "moods": ["epic", "warm"],
        "tags": ["space", "iss", "astronaut"],
        "base_price_rub": 799,
        "cost_price_rub": 239,
        "estimated_duration_sec": 60,
        "difficulty": 3,
        "personalization_score": 9,
        "sort_order": 24,
    },
    {
        "code": "matrix_style",
        "title": "Матрица",
        "description": "Поздравление в стиле «Матрицы». Зелёный код, буллет-тайм и Нео.",
        "kind": "video",
        "category": "cinematic",
        "occasion_codes": ["birthday"],
        "relationship_types": ["friend", "colleague", "classmate"],
        "moods": ["epic", "brutal"],
        "tags": ["matrix", "scifi", "action"],
        "base_price_rub": 699,
        "cost_price_rub": 209,
        "estimated_duration_sec": 50,
        "difficulty": 3,
        "personalization_score": 8,
        "sort_order": 25,
    },
    {
        "code": "medal_ceremony",
        "title": "Церемония награждения",
        "description": "Торжественная церемония вручения медали за жизненные достижения.",
        "kind": "video",
        "category": "cinematic",
        "occasion_codes": ["birthday", "achievement", "anniversary"],
        "relationship_types": ["parent", "child", "spouse", "partner", "friend", "colleague", "sibling", "grandparent", "grandchild", "classmate", "teacher", "relative"],
        "moods": ["epic", "official"],
        "tags": ["medal", "ceremony", "achievement"],
        "base_price_rub": 799,
        "cost_price_rub": 239,
        "estimated_duration_sec": 55,
        "difficulty": 3,
        "personalization_score": 8,
        "sort_order": 26,
    },
    {
        "code": "news_future",
        "title": "Новости будущего",
        "description": "Именинник в ведущих новостей из будущего. Юмор и предсказания.",
        "kind": "video",
        "category": "cinematic",
        "occasion_codes": ["birthday", "new_year"],
        "relationship_types": ["friend", "colleague", "sibling"],
        "moods": ["funny", "surprising"],
        "tags": ["news", "future", "humor"],
        "base_price_rub": 599,
        "cost_price_rub": 179,
        "estimated_duration_sec": 45,
        "difficulty": 2,
        "personalization_score": 7,
        "sort_order": 27,
    },
    {
        "code": "court_trial",
        "title": "Суд над именинником",
        "description": "Судебное разбиательство с обвинениями в том, что именинник — замечательный человек.",
        "kind": "video",
        "category": "humor",
        "occasion_codes": ["birthday"],
        "relationship_types": ["friend", "colleague", "classmate"],
        "moods": ["funny", "ironic"],
        "tags": ["court", "trial", "humor"],
        "base_price_rub": 599,
        "cost_price_rub": 179,
        "estimated_duration_sec": 50,
        "difficulty": 2,
        "personalization_score": 8,
        "sort_order": 30,
    },
    {
        "code": "interview_star",
        "title": "Интервью со звездой",
        "description": "Именинник в роли звезды на красной дорожке. Эксклюзивное интервью.",
        "kind": "video",
        "category": "humor",
        "occasion_codes": ["birthday", "anniversary"],
        "relationship_types": ["spouse", "partner", "friend"],
        "moods": ["funny", "romantic"],
        "tags": ["interview", "celebrity", "humor"],
        "base_price_rub": 699,
        "cost_price_rub": 209,
        "estimated_duration_sec": 55,
        "difficulty": 3,
        "personalization_score": 8,
        "sort_order": 31,
    },
    {
        "code": "president_address",
        "title": "Президентское обращение",
        "description": "Именинник в роли президента обращается к нации по случаю дня рождения.",
        "kind": "video",
        "category": "humor",
        "occasion_codes": ["birthday", "anniversary"],
        "relationship_types": ["boss", "colleague", "parent"],
        "moods": ["official", "funny"],
        "tags": ["president", "official", "humor"],
        "base_price_rub": 699,
        "cost_price_rub": 209,
        "estimated_duration_sec": 45,
        "difficulty": 2,
        "personalization_score": 7,
        "sort_order": 32,
    },
    {
        "code": "alien_greeting",
        "title": "Инопланетяне",
        "description": "Инопланетяне поздравляют именинника с самой далёкой планеты галактики.",
        "kind": "video",
        "category": "humor",
        "occasion_codes": ["birthday"],
        "relationship_types": ["friend", "classmate", "sibling"],
        "moods": ["funny", "surprising"],
        "tags": ["alien", "scifi", "humor"],
        "base_price_rub": 599,
        "cost_price_rub": 179,
        "estimated_duration_sec": 45,
        "difficulty": 2,
        "personalization_score": 7,
        "sort_order": 33,
    },
    {
        "code": "sport_commentator",
        "title": "Спортивный комментатор",
        "description": "Именинник — чемпион, комментатор ведёт репортаж с победы.",
        "kind": "video",
        "category": "humor",
        "occasion_codes": ["birthday"],
        "relationship_types": ["friend", "colleague", "classmate"],
        "moods": ["funny", "epic"],
        "tags": ["sport", "commentator", "champion"],
        "base_price_rub": 599,
        "cost_price_rub": 179,
        "estimated_duration_sec": 50,
        "difficulty": 2,
        "personalization_score": 7,
        "sort_order": 34,
    },
    {
        "code": "police_protocol",
        "title": "Полицейский протокол",
        "description": "Именинник — подозреваемый, который невиновен, потому что сегодня его день.",
        "kind": "video",
        "category": "humor",
        "occasion_codes": ["birthday"],
        "relationship_types": ["friend", "colleague", "classmate"],
        "moods": ["funny", "brutal"],
        "tags": ["police", "protocol", "humor"],
        "base_price_rub": 599,
        "cost_price_rub": 179,
        "estimated_duration_sec": 50,
        "difficulty": 2,
        "personalization_score": 7,
        "sort_order": 35,
    },
    {
        "code": "military_communique",
        "title": "Военная сводка",
        "description": "Секретная военная сводка о том, что сегодня день рождения героя.",
        "kind": "video",
        "category": "humor",
        "occasion_codes": ["feb23", "victory_day", "birthday"],
        "relationship_types": ["friend", "colleague", "classmate"],
        "moods": ["official", "funny"],
        "tags": ["military", "communique", "humor"],
        "base_price_rub": 599,
        "cost_price_rub": 179,
        "estimated_duration_sec": 50,
        "difficulty": 2,
        "personalization_score": 7,
        "sort_order": 36,
    },
    {
        "code": "documentary_life",
        "title": "Документальный фильм",
        "description": "Документальный фильм о жизни именинника. Трогательно и глубоко.",
        "kind": "video",
        "category": "emotional",
        "occasion_codes": ["birthday", "anniversary", "wedding"],
        "relationship_types": ["parent", "spouse", "sibling"],
        "moods": ["touching", "nostalgic"],
        "tags": ["documentary", "life", "nostalgia"],
        "base_price_rub": 799,
        "cost_price_rub": 239,
        "estimated_duration_sec": 70,
        "difficulty": 3,
        "personalization_score": 9,
        "sort_order": 40,
    },
    {
        "code": "thanks_for_everything",
        "title": "Спасибо за всё",
        "description": "Трогательное поздравление со словами благодарности за всё, что человек сделал.",
        "kind": "video",
        "category": "emotional",
        "occasion_codes": ["birthday", "anniversary"],
        "relationship_types": ["parent", "spouse", "teacher"],
        "moods": ["touching", "warm"],
        "tags": ["gratitude", "thanks", "emotional"],
        "base_price_rub": 699,
        "cost_price_rub": 209,
        "estimated_duration_sec": 55,
        "difficulty": 2,
        "personalization_score": 9,
        "sort_order": 41,
    },
    {
        "code": "rap_battle",
        "title": "Рэп-поздравление",
        "description": "Именинник в роли рэпера читает поздравительный трек. Читка и биты.",
        "kind": "video",
        "category": "music",
        "occasion_codes": ["birthday"],
        "relationship_types": ["friend", "colleague", "classmate"],
        "moods": ["funny", "epic"],
        "tags": ["rap", "music", "hiphop"],
        "base_price_rub": 899,
        "cost_price_rub": 269,
        "estimated_duration_sec": 60,
        "difficulty": 4,
        "personalization_score": 8,
        "sort_order": 50,
    },
    {
        "code": "love_letter",
        "title": "Любовное письмо",
        "description": "Романтическое поздравление в форме любовного письма. Нежно и страстно.",
        "kind": "video",
        "category": "romantic",
        "occasion_codes": ["anniversary", "wedding", "valentines"],
        "relationship_types": ["spouse", "partner"],
        "moods": ["romantic", "touching"],
        "tags": ["love", "letter", "romance"],
        "base_price_rub": 699,
        "cost_price_rub": 209,
        "estimated_duration_sec": 55,
        "difficulty": 2,
        "personalization_score": 9,
        "sort_order": 60,
    },
    {
        "code": "cinematic_love",
        "title": "Кино о любви",
        "description": "Короткометражный фильм о любви. Именинник — главный герой романтики.",
        "kind": "video",
        "category": "romantic",
        "occasion_codes": ["anniversary", "wedding"],
        "relationship_types": ["spouse", "partner"],
        "moods": ["romantic", "warm"],
        "tags": ["cinematic", "love", "movie"],
        "base_price_rub": 799,
        "cost_price_rub": 239,
        "estimated_duration_sec": 60,
        "difficulty": 3,
        "personalization_score": 9,
        "sort_order": 61,
    },
    {
        "code": "romantic_trailer",
        "title": "Романтический трейлер",
        "description": "Трейлер романтического фильма с именниником в главной роли.",
        "kind": "video",
        "category": "romantic",
        "occasion_codes": ["anniversary", "wedding", "valentines"],
        "relationship_types": ["spouse", "partner"],
        "moods": ["romantic", "epic"],
        "tags": ["trailer", "romance", "premiere"],
        "base_price_rub": 799,
        "cost_price_rub": 239,
        "estimated_duration_sec": 55,
        "difficulty": 3,
        "personalization_score": 8,
        "sort_order": 62,
    },
    {
        "code": "couple_journey",
        "title": "Путешествие пары",
        "description": "История путешествия пары через годы. Ностальгия и тепло.",
        "kind": "video",
        "category": "romantic",
        "occasion_codes": ["anniversary", "wedding"],
        "relationship_types": ["spouse", "partner"],
        "moods": ["romantic", "nostalgic"],
        "tags": ["journey", "couple", "nostalgia"],
        "base_price_rub": 699,
        "cost_price_rub": 209,
        "estimated_duration_sec": 50,
        "difficulty": 2,
        "personalization_score": 8,
        "sort_order": 63,
    },
    {
        "code": "how_we_met",
        "title": "История знакомства",
        "description": "Трогательная история того, как пара познакомилась. С юмором и нежностью.",
        "kind": "video",
        "category": "romantic",
        "occasion_codes": ["anniversary", "wedding"],
        "relationship_types": ["spouse", "partner"],
        "moods": ["touching", "nostalgic"],
        "tags": ["meeting", "story", "romance"],
        "base_price_rub": 699,
        "cost_price_rub": 209,
        "estimated_duration_sec": 55,
        "difficulty": 2,
        "personalization_score": 9,
        "sort_order": 64,
    },
    {
        "code": "from_kids_to_parents",
        "title": "От детей родителям",
        "description": "Поздравление от детей родителям. Семейное тепло и благодарность.",
        "kind": "video",
        "category": "family",
        "occasion_codes": ["birthday", "anniversary"],
        "relationship_types": ["child", "parent"],
        "moods": ["touching", "warm"],
        "tags": ["kids", "parents", "family"],
        "base_price_rub": 599,
        "cost_price_rub": 179,
        "estimated_duration_sec": 50,
        "difficulty": 2,
        "personalization_score": 8,
        "sort_order": 70,
    },
    {
        "code": "from_parents_to_child",
        "title": "От родителей ребёнку",
        "description": "Поздравление от родителей ребёнку. Родительская любовь и гордость.",
        "kind": "video",
        "category": "family",
        "occasion_codes": ["birthday", "new_year"],
        "relationship_types": ["parent", "child"],
        "moods": ["warm", "festive"],
        "tags": ["parents", "child", "family"],
        "base_price_rub": 599,
        "cost_price_rub": 179,
        "estimated_duration_sec": 45,
        "difficulty": 1,
        "personalization_score": 7,
        "sort_order": 71,
    },
    {
        "code": "family_chronicles",
        "title": "Семейная хроника",
        "description": "Хроника семьи с архивными кадрами и тёплыми воспоминаниями.",
        "kind": "video",
        "category": "family",
        "occasion_codes": ["birthday", "anniversary"],
        "relationship_types": ["parent", "child", "sibling", "grandparent"],
        "moods": ["nostalgic", "warm"],
        "tags": ["chronicles", "family", "archive"],
        "base_price_rub": 799,
        "cost_price_rub": 239,
        "estimated_duration_sec": 70,
        "difficulty": 3,
        "personalization_score": 8,
        "sort_order": 72,
    },
    {
        "code": "family_movie",
        "title": "Семейный фильм",
        "description": "Фильм о семье с юмором и приключениями. Все члены семьи — герои.",
        "kind": "video",
        "category": "family",
        "occasion_codes": ["birthday", "new_year"],
        "relationship_types": ["parent", "child", "spouse", "partner", "friend", "colleague", "sibling", "grandparent", "grandchild", "classmate", "teacher", "relative"],
        "moods": ["warm", "funny"],
        "tags": ["movie", "family", "adventure"],
        "base_price_rub": 699,
        "cost_price_rub": 209,
        "estimated_duration_sec": 55,
        "difficulty": 2,
        "personalization_score": 7,
        "sort_order": 73,
    },
    {
        "code": "kids_song",
        "title": "Детская песня-поздравление",
        "description": "Весёлая детская песня с анимацией и поздравлением. Для самых маленьких.",
        "kind": "video",
        "category": "family",
        "occasion_codes": ["birthday", "new_year"],
        "relationship_types": ["child", "parent", "grandparent"],
        "moods": ["festive", "funny"],
        "tags": ["kids", "song", "animation"],
        "base_price_rub": 499,
        "cost_price_rub": 149,
        "estimated_duration_sec": 40,
        "difficulty": 1,
        "personalization_score": 6,
        "sort_order": 74,
    },
    {
        "code": "grandparents_touching",
        "title": "Бабушке/дедушке",
        "description": "Трогательное поздравление для бабушек и дедушек. С любовью и уважением.",
        "kind": "video",
        "category": "family",
        "occasion_codes": ["birthday", "anniversary"],
        "relationship_types": ["grandparent"],
        "moods": ["touching", "warm"],
        "tags": ["grandparents", "respect", "love"],
        "base_price_rub": 599,
        "cost_price_rub": 179,
        "estimated_duration_sec": 50,
        "difficulty": 1,
        "personalization_score": 8,
        "sort_order": 75,
    },
    {
        "code": "colleagues_funny",
        "title": "От коллег",
        "description": "Шуточное поздравление от коллектива. Офисные шутки и дружба.",
        "kind": "video",
        "category": "corporate",
        "occasion_codes": ["birthday", "professional_holiday"],
        "relationship_types": ["colleague", "boss", "employee"],
        "moods": ["funny", "official"],
        "tags": ["colleagues", "office", "team"],
        "base_price_rub": 599,
        "cost_price_rub": 179,
        "estimated_duration_sec": 45,
        "difficulty": 2,
        "personalization_score": 7,
        "sort_order": 80,
    },
    {
        "code": "from_boss_to_employee",
        "title": "От руководителя",
        "description": "Официальное поздравление от руководителя. Признание заслуг.",
        "kind": "video",
        "category": "corporate",
        "occasion_codes": ["birthday", "professional_holiday"],
        "relationship_types": ["boss", "employee"],
        "moods": ["official", "warm"],
        "tags": ["boss", "official", "recognition"],
        "base_price_rub": 699,
        "cost_price_rub": 209,
        "estimated_duration_sec": 50,
        "difficulty": 2,
        "personalization_score": 7,
        "sort_order": 81,
    },
    {
        "code": "employee_award",
        "title": "Награда сотруднику",
        "description": "Церемония награждения лучшего сотрудника года. Престиж и признание.",
        "kind": "video",
        "category": "corporate",
        "occasion_codes": ["achievement", "professional_holiday"],
        "relationship_types": ["boss", "employee"],
        "moods": ["official", "epic"],
        "tags": ["award", "employee", "prestige"],
        "base_price_rub": 799,
        "cost_price_rub": 239,
        "estimated_duration_sec": 55,
        "difficulty": 3,
        "personalization_score": 8,
        "sort_order": 82,
    },
    {
        "code": "corporate_news",
        "title": "Корпоративные новости",
        "description": "Именинник в ведущих корпоративных новостей. Юмор и офисные мемы.",
        "kind": "video",
        "category": "corporate",
        "occasion_codes": ["new_year", "professional_holiday"],
        "relationship_types": ["colleague", "boss"],
        "moods": ["official", "funny"],
        "tags": ["news", "corporate", "humor"],
        "base_price_rub": 599,
        "cost_price_rub": 179,
        "estimated_duration_sec": 45,
        "difficulty": 2,
        "personalization_score": 6,
        "sort_order": 83,
    },
    {
        "code": "ceo_greeting",
        "title": "CEO обращается к сотруднику",
        "description": "Видеообращение CEO к сотруднику по случаю дня рождения. Престижно.",
        "kind": "video",
        "category": "corporate",
        "occasion_codes": ["birthday", "anniversary"],
        "relationship_types": ["boss", "employee"],
        "moods": ["official", "warm"],
        "tags": ["ceo", "executive", "greeting"],
        "base_price_rub": 699,
        "cost_price_rub": 209,
        "estimated_duration_sec": 50,
        "difficulty": 2,
        "personalization_score": 7,
        "sort_order": 84,
    },
    {
        "code": "wedding_congrats",
        "title": "С днём свадьбы",
        "description": "Поздравление молодожёнам с днём свадьбы. Любовь и счастье.",
        "kind": "video",
        "category": "wedding",
        "occasion_codes": ["wedding", "anniversary"],
        "relationship_types": ["friend", "spouse", "parent", "sibling"],
        "moods": ["romantic", "warm"],
        "tags": ["wedding", "marriage", "love"],
        "base_price_rub": 699,
        "cost_price_rub": 209,
        "estimated_duration_sec": 55,
        "difficulty": 2,
        "personalization_score": 8,
        "sort_order": 90,
    },
    {
        "code": "retro_ussr",
        "title": "СССР-ретро",
        "description": "Поздравление в стиле советского телевидения. Ретро-атмосфера и ностальгия.",
        "kind": "video",
        "category": "thematic",
        "occasion_codes": ["birthday", "victory_day", "feb23", "march8"],
        "relationship_types": ["parent", "grandparent", "classmate"],
        "moods": ["nostalgic", "funny"],
        "tags": ["retro", "ussr", "vintage"],
        "base_price_rub": 699,
        "cost_price_rub": 209,
        "estimated_duration_sec": 55,
        "difficulty": 2,
        "personalization_score": 8,
        "sort_order": 100,
    },
    {"code": "oscar_award", "title": "Оскар", "kind": "video", "category": "cinematic", "occasion_codes": ["birthday", "anniversary", "achievement"], "relationship_types": RELATIONSHIP_TYPES, "moods": ["epic", "official"], "base_price_rub": 799, "estimated_duration_sec": 55, "difficulty": 3, "personalization_score": 8},
    {"code": "president_address", "title": "Президентское обращение", "kind": "video", "category": "humor", "occasion_codes": ["birthday", "anniversary"], "relationship_types": ["boss", "colleague", "parent"], "moods": ["official", "funny"], "base_price_rub": 699, "estimated_duration_sec": 45, "difficulty": 2, "personalization_score": 7},
    {"code": "space_mission", "title": "Космическая миссия", "kind": "video", "category": "cinematic", "occasion_codes": ["birthday", "new_year"], "relationship_types": ["friend", "partner", "spouse"], "moods": ["epic", "warm"], "base_price_rub": 799, "estimated_duration_sec": 60, "difficulty": 3, "personalization_score": 9},
    {"code": "alien_greeting", "title": "Инопланетяне", "kind": "video", "category": "humor", "occasion_codes": ["birthday"], "relationship_types": ["friend", "classmate", "sibling"], "moods": ["funny", "surprising"], "base_price_rub": 599, "estimated_duration_sec": 45, "difficulty": 2, "personalization_score": 7},
    {"code": "matrix_style", "title": "Матрица", "kind": "video", "category": "cinematic", "occasion_codes": ["birthday"], "relationship_types": ["friend", "colleague", "classmate"], "moods": ["epic", "brutal"], "base_price_rub": 699, "estimated_duration_sec": 50, "difficulty": 3, "personalization_score": 8},
    {"code": "love_letter", "title": "Любовное письмо", "kind": "video", "category": "romantic", "occasion_codes": ["anniversary", "wedding", "valentines"], "relationship_types": ["spouse", "partner"], "moods": ["romantic", "touching"], "base_price_rub": 699, "estimated_duration_sec": 55, "difficulty": 2, "personalization_score": 9},
    {"code": "cinematic_love", "title": "Кино о любви", "kind": "video", "category": "romantic", "occasion_codes": ["anniversary", "wedding"], "relationship_types": ["spouse", "partner"], "moods": ["romantic", "warm"], "base_price_rub": 799, "estimated_duration_sec": 60, "difficulty": 3, "personalization_score": 9},
    {"code": "romantic_trailer", "title": "Романтический трейлер", "kind": "video", "category": "romantic", "occasion_codes": ["anniversary", "wedding", "valentines"], "relationship_types": ["spouse", "partner"], "moods": ["romantic", "epic"], "base_price_rub": 799, "estimated_duration_sec": 55, "difficulty": 3, "personalization_score": 8},
    {"code": "couple_journey", "title": "Путешествие пары", "kind": "video", "category": "romantic", "occasion_codes": ["anniversary", "wedding"], "relationship_types": ["spouse", "partner"], "moods": ["romantic", "nostalgic"], "base_price_rub": 699, "estimated_duration_sec": 50, "difficulty": 2, "personalization_score": 8},
    {"code": "how_we_met", "title": "История знакомства", "kind": "video", "category": "romantic", "occasion_codes": ["anniversary", "wedding"], "relationship_types": ["spouse", "partner"], "moods": ["touching", "nostalgic"], "base_price_rub": 699, "estimated_duration_sec": 55, "difficulty": 2, "personalization_score": 9},
    {"code": "from_kids_to_parents", "title": "От детей родителям", "kind": "video", "category": "family", "occasion_codes": ["birthday", "anniversary"], "relationship_types": ["child", "parent"], "moods": ["touching", "warm"], "base_price_rub": 599, "estimated_duration_sec": 50, "difficulty": 2, "personalization_score": 8},
    {"code": "from_parents_to_child", "title": "От родителей ребёнку", "kind": "video", "category": "family", "occasion_codes": ["birthday", "new_year"], "relationship_types": ["parent", "child"], "moods": ["warm", "festive"], "base_price_rub": 599, "estimated_duration_sec": 45, "difficulty": 1, "personalization_score": 7},
    {"code": "family_chronicles", "title": "Семейная хроника", "kind": "video", "category": "family", "occasion_codes": ["birthday", "anniversary"], "relationship_types": ["parent", "child", "sibling", "grandparent"], "moods": ["nostalgic", "warm"], "base_price_rub": 799, "estimated_duration_sec": 70, "difficulty": 3, "personalization_score": 8},
    {"code": "family_movie", "title": "Семейный фильм", "kind": "video", "category": "family", "occasion_codes": ["birthday", "new_year"], "relationship_types": RELATIONSHIP_TYPES, "moods": ["warm", "funny"], "base_price_rub": 699, "estimated_duration_sec": 55, "difficulty": 2, "personalization_score": 7},
    {"code": "thanks_for_everything", "title": "Спасибо за всё", "kind": "video", "category": "emotional", "occasion_codes": ["birthday", "anniversary"], "relationship_types": ["parent", "spouse", "teacher"], "moods": ["touching", "warm"], "base_price_rub": 699, "estimated_duration_sec": 55, "difficulty": 2, "personalization_score": 9},
    {"code": "colleagues_funny", "title": "От коллег", "kind": "video", "category": "corporate", "occasion_codes": ["birthday", "professional_holiday"], "relationship_types": ["colleague", "boss", "employee"], "moods": ["funny", "official"], "base_price_rub": 599, "estimated_duration_sec": 45, "difficulty": 2, "personalization_score": 7},
    {"code": "from_boss_to_employee", "title": "От руководителя", "kind": "video", "category": "corporate", "occasion_codes": ["birthday", "professional_holiday"], "relationship_types": ["boss", "employee"], "moods": ["official", "warm"], "base_price_rub": 699, "estimated_duration_sec": 50, "difficulty": 2, "personalization_score": 7},
    {"code": "employee_award", "title": "Награда сотруднику", "kind": "video", "category": "corporate", "occasion_codes": ["achievement", "professional_holiday"], "relationship_types": ["boss", "employee"], "moods": ["official", "epic"], "base_price_rub": 799, "estimated_duration_sec": 55, "difficulty": 3, "personalization_score": 8},
    {"code": "corporate_news", "title": "Корпоративные новости", "kind": "video", "category": "corporate", "occasion_codes": ["new_year", "professional_holiday"], "relationship_types": ["colleague", "boss"], "moods": ["official", "funny"], "base_price_rub": 599, "estimated_duration_sec": 45, "difficulty": 2, "personalization_score": 6},
    {"code": "ceo_greeting", "title": "CEO обращается к сотруднику", "kind": "video", "category": "corporate", "occasion_codes": ["birthday", "anniversary"], "relationship_types": ["boss", "employee"], "moods": ["official", "warm"], "base_price_rub": 699, "estimated_duration_sec": 50, "difficulty": 2, "personalization_score": 7},
    {"code": "march8_women", "title": "8 марта — женщине", "kind": "video", "category": "holiday", "occasion_codes": ["march8"], "relationship_types": ["spouse", "parent", "colleague", "friend"], "moods": ["warm", "romantic"], "base_price_rub": 599, "estimated_duration_sec": 45, "difficulty": 1, "personalization_score": 7},
    {"code": "feb23_men", "title": "23 февраля — мужчине", "kind": "video", "category": "holiday", "occasion_codes": ["feb23"], "relationship_types": ["spouse", "parent", "colleague", "friend"], "moods": ["brutal", "official"], "base_price_rub": 599, "estimated_duration_sec": 45, "difficulty": 2, "personalization_score": 7},
    {"code": "new_year_wishes", "title": "Новый год — поздравление", "kind": "video", "category": "holiday", "occasion_codes": ["new_year"], "relationship_types": RELATIONSHIP_TYPES, "moods": ["festive", "warm", "funny"], "base_price_rub": 599, "estimated_duration_sec": 50, "difficulty": 1, "personalization_score": 6},
    {"code": "wedding_congrats", "title": "С днём свадьбы", "kind": "video", "category": "wedding", "occasion_codes": ["wedding", "anniversary"], "relationship_types": ["friend", "spouse", "parent", "sibling"], "moods": ["romantic", "warm"], "base_price_rub": 699, "estimated_duration_sec": 55, "difficulty": 2, "personalization_score": 8},
    {"code": "anniversary_epic", "title": "Юбилей — эпично", "kind": "video", "category": "birthday", "occasion_codes": ["birthday", "anniversary"], "relationship_types": RELATIONSHIP_TYPES, "moods": ["epic", "warm"], "base_price_rub": 799, "estimated_duration_sec": 60, "difficulty": 3, "personalization_score": 8},
    {"code": "kids_song", "title": "Детская песня-поздравление", "kind": "video", "category": "family", "occasion_codes": ["birthday", "new_year"], "relationship_types": ["child", "parent", "grandparent"], "moods": ["festive", "funny"], "base_price_rub": 499, "estimated_duration_sec": 40, "difficulty": 1, "personalization_score": 6},
    {"code": "grandparents_touching", "title": "Бабушке/дедушке", "kind": "video", "category": "family", "occasion_codes": ["birthday", "anniversary"], "relationship_types": ["grandparent"], "moods": ["touching", "warm"], "base_price_rub": 599, "estimated_duration_sec": 50, "difficulty": 1, "personalization_score": 8},
    {"code": "sport_commentator", "title": "Спортивный комментатор", "kind": "video", "category": "humor", "occasion_codes": ["birthday"], "relationship_types": ["friend", "colleague", "classmate"], "moods": ["funny", "epic"], "base_price_rub": 599, "estimated_duration_sec": 50, "difficulty": 2, "personalization_score": 7},
    {"code": "police_protocol", "title": "Полицейский протокол", "kind": "video", "category": "humor", "occasion_codes": ["birthday"], "relationship_types": ["friend", "colleague", "classmate"], "moods": ["funny", "brutal"], "base_price_rub": 599, "estimated_duration_sec": 50, "difficulty": 2, "personalization_score": 7},
    {"code": "military_communique", "title": "Военная сводка", "kind": "video", "category": "humor", "occasion_codes": ["feb23", "victory_day", "birthday"], "relationship_types": ["friend", "colleague", "classmate"], "moods": ["official", "funny"], "base_price_rub": 599, "estimated_duration_sec": 50, "difficulty": 2, "personalization_score": 7},
    {"code": "medal_ceremony", "title": "Церемония награждения", "kind": "video", "category": "cinematic", "occasion_codes": ["birthday", "achievement", "anniversary"], "relationship_types": RELATIONSHIP_TYPES, "moods": ["epic", "official"], "base_price_rub": 799, "estimated_duration_sec": 55, "difficulty": 3, "personalization_score": 8},
    {"code": "retro_ussr", "title": "СССР-ретро", "kind": "video", "category": "thematic", "occasion_codes": ["birthday", "victory_day", "feb23", "march8"], "relationship_types": ["parent", "grandparent", "classmate"], "moods": ["nostalgic", "funny"], "base_price_rub": 699, "estimated_duration_sec": 55, "difficulty": 2, "personalization_score": 8},
]


async def seed():
    async with async_session_factory() as db:
        # Seed relationship types
        for code in RELATIONSHIP_TYPES:
            existing = await db.execute(
                __import__("sqlalchemy").select(RelationshipType).where(RelationshipType.code == code)
            )
            if existing.scalar_one_or_none():
                continue
            db.add(RelationshipType(code=code, title=code.title(), sort_order=RELATIONSHIP_TYPES.index(code), is_active=True))

        # Seed holidays
        for holiday in HOLIDAYS:
            existing = await db.execute(
                __import__("sqlalchemy").select(Holiday).where(Holiday.code == holiday["code"])
            )
            if existing.scalar_one_or_none():
                continue
            db.add(Holiday(**holiday, status="active", metadata_={}))

        # Seed templates
        for tpl_data in FIRST_TEMPLATES:
            existing = await db.execute(
                __import__("sqlalchemy").select(Template).where(Template.code == tpl_data["code"])
            )
            if existing.scalar_one_or_none():
                print(f"Template '{tpl_data['code']}' already exists, skipping")
                continue

            template_id = uuid.uuid4()
            template = Template(
                id=template_id,
                code=tpl_data["code"],
                title=tpl_data["title"],
                description=tpl_data.get("description"),
                kind=tpl_data["kind"],
                status="published",
                category=tpl_data.get("category"),
                occasion_codes=tpl_data.get("occasion_codes", []),
                relationship_types=tpl_data.get("relationship_types", []),
                moods=tpl_data.get("moods", []),
                tags=tpl_data.get("tags", []),
                base_price_rub=tpl_data.get("base_price_rub", 0),
                cost_price_rub=tpl_data.get("cost_price_rub", 0),
                estimated_duration_sec=tpl_data.get("estimated_duration_sec"),
                difficulty=tpl_data.get("difficulty"),
                personalization_score=tpl_data.get("personalization_score"),
                sort_order=tpl_data.get("sort_order", 0),
            )
            db.add(template)
            await db.flush()

            version = TemplateVersion(
                template_id=template.id,
                version=1,
                status="published",
                schema_version="1.0",
                prompt_config={"system_prompt": "Ты — режиссёр видеопоздравлений.", "temperature": 0.7},
                render_config={"resolution": "1080p", "fps": 30},
                personalization_config={"max_variables": 10},
                validation_config={"min_length_sec": 15, "max_length_sec": 120},
                max_duration_sec=120,
                qa_checklist={
                    "script_checked": True,
                    "face_ok": True,
                    "voice_ok": True,
                    "text_ok": True,
                    "duration_ok": True,
                    "cost_known": True,
                },
                variant_group=f"{tpl_data['category']}_v1",
                variant_name="control",
                published_at=datetime.now(UTC),
            )
            db.add(version)
            await db.flush()

            scene = Scene(
                template_id=template.id,
                code="main_scene",
                title="Основная сцена",
                source_type="ai_generated",
                rights_status="cleared",
                duration_sec=tpl_data.get("estimated_duration_sec"),
                scene_config={"camera": "medium_shot", "lighting": "warm"},
                condition={
                    "field": "recipient.age",
                    "operator": ">=",
                    "value": 18,
                    "then": "main_scene",
                    "else": "main_scene_soft",
                },
            )
            db.add(scene)
            print(f"Created template: {tpl_data['code']}")

        await db.commit()
        print("Seed completed successfully!")


if __name__ == "__main__":
    asyncio.run(seed())
